### PR TITLE
Provisional 2.x 

### PR DESCRIPTION
**Pull request by davedevelopment**
I picked this as an easy target to help me write some docs for upgrading providers to the 2.x API.

### CODE REVIEW

**Comment by jeremeamia** [comment]
I apologize that we missed this submission, Dave. What's the status on Silex 2, anyway?

**Comment by davedevelopment** [comment]
I don't know what the status of 2.0 is, but Fabien's put quite a bit of work in the last few days and he usually does that before prepping a Silex release.

**Comment by mvanbaak** [comment]
silex 2 is out. Can we get this one up-to-date and merged? Thanks.

**Comment by cjyclaire** [comment]
Close this with PR #12

**Pull request closed without merging**
